import jsPDF from 'jspdf';
import { Invoice } from '@/types/invoice';
import { format } from 'date-fns';
import { formatCurrencyForPDF } from '@/lib/currency';

// --- CONFIGURATION ---
const PAGE = {
  margin: 18,
  footerHeight: 15,
};

// Modern Color Palette
const C = {
  primary: [249, 115, 22] as [number, number, number],     // Brand Orange
  primaryLight: [255, 237, 213] as [number, number, number], // Orange tint
  dark: [15, 23, 42] as [number, number, number],           // Slate 900
  text: [51, 65, 85] as [number, number, number],           // Slate 600
  muted: [148, 163, 184] as [number, number, number],       // Slate 400
  border: [226, 232, 240] as [number, number, number],      // Slate 200
  bg: [248, 250, 252] as [number, number, number],          // Slate 50
  white: [255, 255, 255] as [number, number, number],
  green: [22, 163, 74] as [number, number, number],         // Green 600
  blue: [37, 99, 235] as [number, number, number],          // Blue 600
};

export const generateInvoicePDF = (invoice: Invoice, removeBranding: boolean = false): void => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const pw = doc.internal.pageSize.getWidth();   // page width
  const ph = doc.internal.pageSize.getHeight();   // page height
  const cw = pw - PAGE.margin * 2;                // content width
  const ml = PAGE.margin;                          // margin left
  const mr = pw - PAGE.margin;                     // margin right

  let y = PAGE.margin;
  let pageNum = 1;

  // ── Helpers ──────────────────────────────────────────

  const txt = (
    text: string | number,
    x: number,
    yPos: number,
    opts: {
      size?: number;
      color?: [number, number, number];
      bold?: boolean;
      align?: 'left' | 'center' | 'right';
      maxWidth?: number;
    } = {}
  ): number => {
    const { size = 9, color = C.text, bold = false, align = 'left', maxWidth } = opts;
    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    const s = String(text ?? '');
    const lineH = size * 0.3527 * 1.5;

    if (maxWidth) {
      const lines = doc.splitTextToSize(s, maxWidth);
      doc.text(lines, x, yPos, { align, baseline: 'top' } as any);
      return lines.length * lineH;
    }
    doc.text(s, x, yPos, { align, baseline: 'top' } as any);
    return lineH;
  };

  const money = (amount: number, currency: string) => formatCurrencyForPDF(amount, currency);

  const line = (x1: number, yPos: number, x2: number, color: [number, number, number] = C.border, width = 0.3) => {
    doc.setDrawColor(color[0], color[1], color[2]);
    doc.setLineWidth(width);
    doc.line(x1, yPos, x2, yPos);
  };

  const rect = (x: number, yPos: number, w: number, h: number, color: [number, number, number], radius = 0) => {
    doc.setFillColor(color[0], color[1], color[2]);
    if (radius > 0) {
      doc.roundedRect(x, yPos, w, h, radius, radius, 'F');
    } else {
      doc.rect(x, yPos, w, h, 'F');
    }
  };

  const drawFooter = (pNum: number) => {
    const fy = ph - 12;
    line(ml, fy - 3, mr, C.border, 0.3);
    
    if (!removeBranding) {
      txt('Generated by InvoicePak', pw / 2, fy, { size: 7, color: C.muted, align: 'center' });
    }
    txt(`Page ${pNum}`, mr, fy, { size: 7, color: C.muted, align: 'right' });
  };

  const checkBreak = (needed: number): boolean => {
    if (y + needed > ph - PAGE.footerHeight - 5) {
      drawFooter(pageNum);
      doc.addPage();
      pageNum++;
      y = PAGE.margin;
      return true;
    }
    return false;
  };

  // ══════════════════════════════════════════════════════
  // HEADER
  // ══════════════════════════════════════════════════════

  // Logo / Company Name
  if (invoice.companyLogo) {
    try {
      doc.addImage(invoice.companyLogo, 'AUTO', ml, y, 30, 12);
      if (invoice.companyName) {
        txt(invoice.companyName, ml, y + 14, { size: 11, bold: true, color: C.dark });
      }
    } catch {
      txt(invoice.companyName || 'INVOICE', ml, y + 3, { size: 20, bold: true, color: C.primary });
    }
  } else {
    const brandName = invoice.companyName || (!removeBranding ? 'InvoicePak' : invoice.senderName || 'INVOICE');
    txt(brandName, ml, y + 3, { size: 20, bold: true, color: C.primary });
  }

  // Right side: INVOICE title
  txt('INVOICE', mr, y + 2, { size: 26, bold: true, color: C.dark, align: 'right' });
  txt(`# ${invoice.invoiceNumber || 'DRAFT'}`, mr, y + 14, { size: 10, bold: true, color: C.text, align: 'right' });

  y += 28;

  // Orange accent line
  rect(ml, y, cw, 1.2, C.primary);
  y += 8;

  // ══════════════════════════════════════════════════════
  // INFO SECTION (FROM / BILL TO / DATES)
  // ══════════════════════════════════════════════════════

  const infoStartY = y;

  // FROM
  txt('FROM', ml, y, { size: 7, bold: true, color: C.primary });
  y += 4;
  const fromH = txt(invoice.senderName || 'Sender', ml, y, { size: 10, bold: true, color: C.dark, maxWidth: 55 });

  // BILL TO
  const col2 = ml + 65;
  txt('BILL TO', col2, infoStartY, { size: 7, bold: true, color: C.primary });
  const toH = txt(invoice.clientName || 'Client', col2, infoStartY + 4, { size: 10, bold: true, color: C.dark, maxWidth: 55 });

  // DATE BOX (Right aligned)
  const boxW = 62;
  const boxX = mr - boxW;
  const boxH = 32;
  rect(boxX, infoStartY - 2, boxW, boxH, C.bg, 3);

  const bx = boxX + 5;
  const bvx = mr - 5;
  let by = infoStartY + 3;

  // Status
  txt('Status', bx, by, { size: 8, color: C.muted });
  const statusStr = (invoice.status || 'draft').toUpperCase();
  const statusColor = invoice.status === 'paid' ? C.green : invoice.status === 'sent' ? C.blue : C.muted;
  txt(statusStr, bvx, by, { size: 8, bold: true, color: statusColor, align: 'right' });

  by += 8;
  // Invoice Date
  const safeDate = invoice.invoiceDate ? new Date(invoice.invoiceDate) : new Date();
  txt('Date', bx, by, { size: 8, color: C.muted });
  txt(isNaN(safeDate.getTime()) ? 'N/A' : format(safeDate, 'dd MMM yyyy'), bvx, by, { size: 8, bold: true, color: C.dark, align: 'right' });

  by += 8;
  // Due Date
  const safeDue = invoice.dueDate ? new Date(invoice.dueDate) : null;
  txt('Due Date', bx, by, { size: 8, color: C.muted });
  txt(safeDue && !isNaN(safeDue.getTime()) ? format(safeDue, 'dd MMM yyyy') : 'N/A', bvx, by, { size: 8, bold: true, color: C.dark, align: 'right' });

  y = Math.max(infoStartY + fromH + 8, infoStartY + toH + 8, infoStartY + boxH + 4);

  // ══════════════════════════════════════════════════════
  // PROJECT DESCRIPTION
  // ══════════════════════════════════════════════════════

  if (invoice.serviceDescription) {
    checkBreak(25);
    y += 4;
    txt('PROJECT DESCRIPTION', ml, y, { size: 7, bold: true, color: C.primary });
    y += 5;
    const dH = txt(invoice.serviceDescription, ml, y, { size: 9, maxWidth: cw, color: C.text });
    y += dH + 6;
  }

  // ══════════════════════════════════════════════════════
  // ITEMS TABLE
  // ══════════════════════════════════════════════════════

  const hasItems = invoice.items && invoice.items.length > 0;

  if (hasItems) {
    checkBreak(20);
    y += 2;

    // Column positions
    const descX = ml + 3;
    const descW = cw * 0.48;
    const qtyX = ml + cw * 0.58;
    const rateX = ml + cw * 0.75;
    const amtX = mr - 3;

    // Table Header
    const drawHeader = (curY: number) => {
      rect(ml, curY, cw, 9, C.dark, 1.5);
      const hy = curY + 2.5;
      txt('DESCRIPTION', descX, hy, { size: 7.5, bold: true, color: C.white });
      txt('QTY', qtyX, hy, { size: 7.5, bold: true, color: C.white, align: 'center' });
      txt('RATE', rateX, hy, { size: 7.5, bold: true, color: C.white, align: 'right' });
      txt('AMOUNT', amtX, hy, { size: 7.5, bold: true, color: C.white, align: 'right' });
      return 9;
    };

    y += drawHeader(y);

    invoice.items!.forEach((item, idx) => {
      const descText = item.description || 'No description';
      doc.setFontSize(9);
      const lines = doc.splitTextToSize(descText, descW);
      const rowH = Math.max(lines.length * 5, 8) + 5;

      if (checkBreak(rowH)) {
        y += drawHeader(y);
      }

      // Zebra striping
      if (idx % 2 === 0) {
        rect(ml, y, cw, rowH, C.bg);
      }

      const ty = y + 3;

      // Description
      doc.setFontSize(9);
      doc.setTextColor(C.text[0], C.text[1], C.text[2]);
      doc.setFont('helvetica', 'normal');
      doc.text(lines, descX, ty, { baseline: 'top' } as any);

      // Qty, Rate, Amount
      txt(String(item.quantity || 0), qtyX, ty, { size: 9, color: C.text, align: 'center' });
      txt(money(item.rate || 0, invoice.currency), rateX, ty, { size: 9, color: C.text, align: 'right' });
      txt(money(item.amount || 0, invoice.currency), amtX, ty, { size: 9, bold: true, color: C.dark, align: 'right' });

      y += rowH;

      // Row border
      line(ml, y, mr, C.border, 0.15);
    });
  } else {
    // No items — show single amount
    checkBreak(20);
    y += 4;
    txt('TOTAL AMOUNT', ml, y, { size: 7, bold: true, color: C.primary });
    y += 5;
    txt(money(invoice.amount || 0, invoice.currency), ml, y, { size: 16, bold: true, color: C.dark });
    y += 12;
  }

  y += 10;

  // ══════════════════════════════════════════════════════
  // TOTALS + NOTES
  // ══════════════════════════════════════════════════════

  checkBreak(55);

  const totalAmount = hasItems
    ? invoice.items!.reduce((sum, item) => sum + (item.amount || 0), 0)
    : (invoice.amount || 0);

  const convRate = invoice.conversionRate || 1;
  const invoiceCurr = invoice.currency || 'USD';
  
  // Determine converted currency and amount based on invoice currency
  let convertedAmt: number;
  let convertedCurr: string;
  let rateLabel: string;

  if (invoiceCurr === 'PKR') {
    // PKR invoice → show USD equivalent
    convertedAmt = totalAmount / convRate;
    convertedCurr = 'USD';
    rateLabel = `1 USD = ${convRate.toFixed(2)} PKR`;
  } else {
    // Any non-PKR currency → show PKR equivalent
    convertedAmt = totalAmount * convRate;
    convertedCurr = 'PKR';
    rateLabel = `1 ${invoiceCurr} = ${convRate.toFixed(2)} PKR`;
  }

  // Notes (left side)
  if (invoice.notes) {
    txt('NOTES', ml, y, { size: 7, bold: true, color: C.primary });
    txt(invoice.notes, ml, y + 5, { size: 8, maxWidth: cw * 0.48, color: C.muted });
  }

  const shouldShowExchange = invoice.showExchangeRate !== false;

  // Totals box (right side)
  const totW = cw * 0.42;
  const totX = mr - totW;
  const totBoxH = shouldShowExchange ? 48 : 22;

  rect(totX, y - 2, totW, totBoxH, C.bg, 3);

  let tY = y + 4;
  const tl = totX + 6;
  const tv = mr - 6;

  if (shouldShowExchange) {
    // Subtotal in invoice currency
    txt(`Subtotal (${invoiceCurr})`, tl, tY, { size: 9, color: C.text });
    txt(money(totalAmount, invoiceCurr), tv, tY, { size: 9, bold: true, color: C.dark, align: 'right' });

    tY += 9;
    // Exchange rate
    txt('Exchange Rate', tl, tY, { size: 9, color: C.muted });
    txt(rateLabel, tv, tY, { size: 8, color: C.text, align: 'right' });

    tY += 9;
    // Divider
    line(tl, tY, tv, C.border, 0.3);

    tY += 6;
    // Total in converted currency (highlighted)
    rect(totX + 3, tY - 3, totW - 6, 14, C.primaryLight, 2);
    txt(`Total (${convertedCurr})`, tl + 2, tY, { size: 10, bold: true, color: C.primary });
    txt(money(convertedAmt, convertedCurr), tv - 2, tY, { size: 13, bold: true, color: C.primary, align: 'right' });
  } else {
    // Just show total in invoice currency
    rect(totX + 3, tY - 3, totW - 6, 14, C.primaryLight, 2);
    txt(`Total (${invoiceCurr})`, tl + 2, tY, { size: 10, bold: true, color: C.primary });
    txt(money(totalAmount, invoiceCurr), tv - 2, tY, { size: 13, bold: true, color: C.primary, align: 'right' });
  }

  // ── Thank You ──
  y = Math.max(y + 55, tY + 20);
  checkBreak(15);
  txt('Thank you for your business!', pw / 2, y, { size: 9, color: C.muted, align: 'center' });

  // Footer
  drawFooter(pageNum);

  // Save
  doc.save(`Invoice-${invoice.invoiceNumber || 'draft'}.pdf`);
};
