import jsPDF from 'jspdf';
import { Invoice } from '@/types/invoice';
import { format } from 'date-fns';
import { formatCurrencyForPDF } from '@/lib/currency';

// --- CONFIGURATION & STYLING ---
const PAGE_CONFIG = {
  format: 'a4',
  unit: 'mm',
  margin: 15,
  lineHeight: 1.2, // Improved line height for readability
};

// Professional Color Palette
const COLORS = {
  primary: [249, 115, 22] as [number, number, number],    // Brand Orange
  secondary: [15, 23, 42] as [number, number, number],    // Dark Slate
  text: [51, 65, 85] as [number, number, number],         // Normal Text
  lightText: [100, 116, 139] as [number, number, number], // Muted Text
  border: [226, 232, 240] as [number, number, number],    // Light Borders
  accentBg: [248, 250, 252] as [number, number, number],  // Light Gray BG
  white: [255, 255, 255] as [number, number, number],
  success: [34, 197, 94] as [number, number, number],
  info: [59, 130, 246] as [number, number, number],
};

export const generateInvoicePDF = (invoice: Invoice, removeBranding: boolean = false): void => {
  // Initialize PDF
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // Dimensions
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - (PAGE_CONFIG.margin * 2);
  
  // State
  let y = PAGE_CONFIG.margin;
  let pageNumber = 1;

  // --- HELPER FUNCTIONS ---

  // 1. Text Writer with Strict Wrapping
  const drawText = (
    text: string | number,
    x: number,
    yPos: number,
    options: {
      size?: number;
      color?: [number, number, number];
      weight?: 'normal' | 'bold';
      align?: 'left' | 'center' | 'right';
      maxWidth?: number; 
    } = {}
  ) => {
    const { 
      size = 9, 
      color = COLORS.text, 
      weight = 'normal', 
      align = 'left', 
      maxWidth 
    } = options;

    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
    doc.setFont('helvetica', weight);

    const safeText = String(text || '');

    if (maxWidth) {
      // Split text to fit width
      const lines = doc.splitTextToSize(safeText, maxWidth);
      doc.text(lines, x, yPos, { align, baseline: 'top' });
      // Return exact height used
      const lineHeightMm = size * 0.3527 * 1.5; 
      return lines.length * lineHeightMm; 
    } else {
      doc.text(safeText, x, yPos, { align, baseline: 'top' });
      return size * 0.3527 * 1.5;
    }
  };

  // 2. Format Currency
  const formatMoney = (amount: number, currency: string) => {
    return formatCurrencyForPDF(amount, currency);
  };

  // 3. Draw Footer
  const drawFooter = (pageNum: number) => {
    const footerY = pageHeight - 15;
    
    doc.setDrawColor(COLORS.border[0], COLORS.border[1], COLORS.border[2]);
    doc.setLineWidth(0.5);
    doc.line(PAGE_CONFIG.margin, footerY - 5, pageWidth - PAGE_CONFIG.margin, footerY - 5);

    drawText(`Page ${pageNum}`, pageWidth / 2, footerY, { 
      size: 8, 
      color: COLORS.lightText, 
      align: 'center' 
    });

    if (!removeBranding) {
      drawText('Generated by InvoicePak', pageWidth - PAGE_CONFIG.margin, footerY, { 
        size: 7, 
        color: COLORS.lightText, 
        align: 'right' 
      });
    }
  };

  // 4. Page Break Logic
  const checkPageBreak = (requiredHeight: number) => {
    if (y + requiredHeight > pageHeight - 20) {
      drawFooter(pageNumber);
      doc.addPage();
      pageNumber++;
      y = PAGE_CONFIG.margin;
      return true;
    }
    return false;
  };

  // --- START GENERATION ---

  // === HEADER ===
  const rightColX = pageWidth - PAGE_CONFIG.margin;

  // Render Logo or Text
  if (invoice.companyLogo) {
    try {
      doc.addImage(invoice.companyLogo, 'AUTO', PAGE_CONFIG.margin, y, 35, 15);
      if (invoice.companyName) {
        drawText(invoice.companyName, PAGE_CONFIG.margin, y + 20, { 
          size: 12, 
          weight: 'bold', 
          color: COLORS.secondary 
        });
      }
    } catch (e) {
      // Fallback
      drawText(invoice.companyName || 'INVOICE', PAGE_CONFIG.margin, y + 5, { 
        size: 18, 
        weight: 'bold', 
        color: COLORS.secondary 
      });
    }
  } else {
    drawText(invoice.companyName || (!removeBranding ? 'InvoicePak' : invoice.senderName || 'INVOICE'), PAGE_CONFIG.margin, y + 5, { 
      size: 18, 
      weight: 'bold', 
      color: COLORS.primary 
    });
  }

  // Invoice Label (Right Side)
  drawText('INVOICE', rightColX, y + 5, { 
    size: 24, 
    weight: 'bold', 
    color: COLORS.secondary, 
    align: 'right' 
  });
  
  drawText(`# ${invoice.invoiceNumber}`, rightColX, y + 15, { 
    size: 10, 
    weight: 'bold', 
    color: COLORS.text, 
    align: 'right' 
  });

  y += 30; // Move down after header

  // Divider
  doc.setDrawColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  doc.setLineWidth(0.8);
  doc.line(PAGE_CONFIG.margin, y, pageWidth - PAGE_CONFIG.margin, y);
  y += 10;

  // === DETAILS SECTION ===
  const col1X = PAGE_CONFIG.margin;
  const col2X = PAGE_CONFIG.margin + 70;
  const col3X = pageWidth - PAGE_CONFIG.margin - 65;

  // FROM
  drawText('FROM:', col1X, y, { size: 8, weight: 'bold', color: COLORS.lightText });
  const fromHeight = drawText(invoice.senderName || '', col1X, y + 5, { 
    size: 10, 
    weight: 'bold', 
    maxWidth: 60 
  });

  // BILL TO
  drawText('BILL TO:', col2X, y, { size: 8, weight: 'bold', color: COLORS.lightText });
  const toHeight = drawText(invoice.clientName || '', col2X, y + 5, { 
    size: 10, 
    weight: 'bold', 
    maxWidth: 60 
  });

  // DATES BOX (Right)
  doc.setFillColor(COLORS.accentBg[0], COLORS.accentBg[1], COLORS.accentBg[2]);
  doc.roundedRect(col3X, y - 2, 65, 30, 2, 2, 'F');
  
  const boxPadX = col3X + 5;
  const boxPadY = y + 3;
  const boxValX = pageWidth - PAGE_CONFIG.margin - 5;

  // Status
  drawText('Status:', boxPadX, boxPadY, { size: 9 });
  const statusColor = invoice.status === 'paid' ? COLORS.success : COLORS.info;
  drawText(invoice.status.toUpperCase(), boxValX, boxPadY, { 
    size: 9, weight: 'bold', color: statusColor, align: 'right' 
  });

  // Date
  drawText('Date:', boxPadX, boxPadY + 7, { size: 9 });
  drawText(format(new Date(invoice.invoiceDate), 'dd MMM yyyy'), boxValX, boxPadY + 7, { 
    size: 9, weight: 'bold', align: 'right' 
  });

  // Due
  drawText('Due Date:', boxPadX, boxPadY + 14, { size: 9 });
  drawText(format(new Date(invoice.dueDate), 'dd MMM yyyy'), boxValX, boxPadY + 14, { 
    size: 9, weight: 'bold', align: 'right' 
  });

  y = Math.max(y + fromHeight + 10, y + toHeight + 10, y + 35); // Safe push down

  // === PROJECT DESCRIPTION ===
  if (invoice.serviceDescription) {
    checkPageBreak(30);
    drawText('PROJECT DESCRIPTION', PAGE_CONFIG.margin, y, { size: 8, weight: 'bold', color: COLORS.lightText });
    y += 5;
    const descH = drawText(invoice.serviceDescription, PAGE_CONFIG.margin, y, { 
      size: 9, 
      maxWidth: contentWidth 
    });
    y += descH + 10;
  }

  // === ITEMS TABLE (FIXED) ===
  if (invoice.items && invoice.items.length > 0) {
    // Define Columns
    const cols = {
      desc: { x: PAGE_CONFIG.margin + 2, w: contentWidth * 0.45 },
      qty: { x: pageWidth - PAGE_CONFIG.margin - 65, w: 15, align: 'center' },
      rate: { x: pageWidth - PAGE_CONFIG.margin - 35, w: 25, align: 'right' },
      amount: { x: pageWidth - PAGE_CONFIG.margin - 2, w: 30, align: 'right' }
    };

    const drawTableHeader = (curY: number) => {
      doc.setFillColor(COLORS.secondary[0], COLORS.secondary[1], COLORS.secondary[2]);
      doc.rect(PAGE_CONFIG.margin, curY, contentWidth, 8, 'F');
      const ty = curY + 2;
      drawText('DESCRIPTION', cols.desc.x, ty, { size: 8, weight: 'bold', color: COLORS.white });
      drawText('QTY', cols.qty.x, ty, { size: 8, weight: 'bold', color: COLORS.white, align: 'right' }); // Fix alignment logic for Qty
      drawText('RATE', cols.rate.x, ty, { size: 8, weight: 'bold', color: COLORS.white, align: 'right' });
      drawText('AMOUNT', cols.amount.x, ty, { size: 8, weight: 'bold', color: COLORS.white, align: 'right' });
      return 8;
    };

    y += drawTableHeader(y);

    invoice.items.forEach((item, index) => {
      const padding = 4;
      
      // Calculate Height Needed based on Description
      // We perform a dummy calculation first
      const descLines = doc.splitTextToSize(item.description, cols.desc.w);
      const lineHeight = 4; // approximate height per line
      const neededHeight = (descLines.length * lineHeight) + (padding * 2); 
      
      // Check Break
      if (checkPageBreak(neededHeight)) {
        y += drawTableHeader(y);
      }

      // Background Striping
      if (index % 2 === 0) {
        doc.setFillColor(COLORS.accentBg[0], COLORS.accentBg[1], COLORS.accentBg[2]);
        doc.rect(PAGE_CONFIG.margin, y, contentWidth, neededHeight, 'F');
      }

      // Draw Content
      const textY = y + padding;

      // Description (Wrapped)
      doc.setFontSize(9);
      doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
      doc.text(descLines, cols.desc.x, textY);

      // Numbers
      drawText(item.quantity.toString(), cols.qty.x, textY, { size: 9, align: 'right' });
      drawText(formatMoney(item.rate, invoice.currency), cols.rate.x, textY, { size: 9, align: 'right' });
      drawText(formatMoney(item.amount, invoice.currency), cols.amount.x, textY, { size: 9, weight: 'bold', align: 'right' });

      y += neededHeight;

      // Border line
      doc.setDrawColor(COLORS.border[0], COLORS.border[1], COLORS.border[2]);
      doc.setLineWidth(0.1);
      doc.line(PAGE_CONFIG.margin, y, pageWidth - PAGE_CONFIG.margin, y);
    });
  }

  y += 10;

  // === TOTALS SECTION ===
  checkPageBreak(50); // Ensure space for totals

  const totalAmount = invoice.items 
    ? invoice.items.reduce((sum, item) => sum + item.amount, 0) 
    : invoice.amount;
  
  const convertedAmount = invoice.currency === 'USD' 
    ? totalAmount * invoice.conversionRate 
    : totalAmount / invoice.conversionRate;
  const convertedCurrency = invoice.currency === 'USD' ? 'PKR' : 'USD';

  // Notes (Left)
  if (invoice.notes) {
    drawText('NOTES:', PAGE_CONFIG.margin, y, { size: 8, weight: 'bold', color: COLORS.lightText });
    drawText(invoice.notes, PAGE_CONFIG.margin, y + 5, { 
      size: 8, 
      maxWidth: contentWidth * 0.5, 
      color: COLORS.lightText 
    });
  }

  // Totals Box (Right)
  const totalsW = contentWidth * 0.4;
  const totalsX = pageWidth - PAGE_CONFIG.margin - totalsW;
  
  doc.setFillColor(COLORS.accentBg[0], COLORS.accentBg[1], COLORS.accentBg[2]);
  doc.roundedRect(totalsX, y, totalsW, 40, 2, 2, 'F');

  let tY = y + 5;
  const tLabelX = totalsX + 5;
  const tValX = pageWidth - PAGE_CONFIG.margin - 5;

  drawText(`Subtotal (${invoice.currency})`, tLabelX, tY, { size: 9 });
  drawText(formatMoney(totalAmount, invoice.currency), tValX, tY, { size: 9, weight: 'bold', align: 'right' });

  tY += 8;
  drawText('Exchange Rate', tLabelX, tY, { size: 9 });
  drawText(`1 USD = ${invoice.conversionRate.toFixed(2)} PKR`, tValX, tY, { size: 9, align: 'right' });

  tY += 8;
  doc.setDrawColor(COLORS.border[0], COLORS.border[1], COLORS.border[2]);
  doc.line(totalsX + 5, tY, pageWidth - PAGE_CONFIG.margin - 5, tY);
  
  tY += 5;
  drawText(`Total (${convertedCurrency})`, tLabelX, tY, { size: 10, weight: 'bold', color: COLORS.primary });
  drawText(formatMoney(convertedAmount, convertedCurrency), tValX, tY, { size: 12, weight: 'bold', color: COLORS.primary, align: 'right' });

  // Final Footer
  drawFooter(pageNumber);

  // Download
  doc.save(`Invoice-${invoice.invoiceNumber || 'draft'}.pdf`);
};
