import jsPDF from 'jspdf';
import { Invoice } from '@/types/invoice';
import { format } from 'date-fns';

// --- CONFIGURATION & STYLING ---
const PAGE_CONFIG = {
  format: 'a4',
  unit: 'mm',
  margin: 15, // margins
  lineHeight: 6, // spacing between lines
};

// Professional Color Palette
const COLORS = {
  primary: [249, 115, 22] as [number, number, number],    // Brand Orange
  secondary: [15, 23, 42] as [number, number, number],    // Dark Slate (Headings)
  text: [51, 65, 85] as [number, number, number],         // Normal Text
  lightText: [100, 116, 139] as [number, number, number], // Muted Text
  border: [226, 232, 240] as [number, number, number],    // Light Borders
  accentBg: [248, 250, 252] as [number, number, number],  // Light Gray BG
  white: [255, 255, 255] as [number, number, number],
  success: [34, 197, 94] as [number, number, number],     // Green
  info: [59, 130, 246] as [number, number, number],       // Blue
};

export const generateInvoicePDF = (invoice: Invoice, removeBranding: boolean = false): void => {
  // Initialize PDF
  const doc = new jsPDF({
    orientation: 'portrait' as const,
    unit: PAGE_CONFIG.unit as 'mm',
    format: PAGE_CONFIG.format as 'a4',
  });

  // Dimensions
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - (PAGE_CONFIG.margin * 2);
  const rightColX = pageWidth - PAGE_CONFIG.margin;
  
  // State
  let y = PAGE_CONFIG.margin;
  let pageNumber = 1;

  // --- HELPER FUNCTIONS ---

  // 1. Text Writer with Auto-Wrap support
  const drawText = (
    text: string | number,
    x: number,
    yPos: number,
    options: {
      size?: number;
      color?: [number, number, number];
      weight?: 'normal' | 'bold';
      align?: 'left' | 'center' | 'right';
      maxWidth?: number; // If provided, text will wrap
    } = {}
  ) => {
    const { 
      size = 9, 
      color = COLORS.text, 
      weight = 'normal', 
      align = 'left', 
      maxWidth 
    } = options;

    doc.setFontSize(size);
    doc.setTextColor(...color);
    doc.setFont('helvetica', weight);

    if (maxWidth) {
      const lines = doc.splitTextToSize(String(text), maxWidth);
      doc.text(lines, x, yPos, { align });
      // Return height consumed by text
      return lines.length * (size * 0.3527 + 1.5); 
    } else {
      doc.text(String(text), x, yPos, { align });
      return size * 0.3527 + 2;
    }
  };

  // 2. Format Currency
  const formatMoney = (amount: number, currency: string) => {
    return new Intl.NumberFormat('en-PK', {
      style: 'currency',
      currency: currency,
      minimumFractionDigits: 0,
      maximumFractionDigits: 2,
    }).format(amount);
  };

  // 3. Draw Footer (Page Number)
  const drawFooter = (pageNum: number) => {
    const footerY = pageHeight - 12;
    
    // Top Border Line
    doc.setDrawColor(...COLORS.border);
    doc.setLineWidth(0.5);
    doc.line(PAGE_CONFIG.margin, footerY - 5, pageWidth - PAGE_CONFIG.margin, footerY - 5);

    // Page Info
    drawText(`Page ${pageNum}`, pageWidth / 2, footerY, { 
      size: 8, 
      color: COLORS.lightText, 
      align: 'center' 
    });

    // Branding in footer
    if (!removeBranding) {
      drawText('Generated by InvoicePK', pageWidth - PAGE_CONFIG.margin, footerY, { 
        size: 7, 
        color: COLORS.lightText, 
        align: 'right' 
      });
    }
  };

  // 4. Page Break Logic
  const checkPageBreak = (requiredHeight: number) => {
    if (y + requiredHeight > pageHeight - 20) {
      drawFooter(pageNumber); // Close current page
      doc.addPage();
      pageNumber++;
      y = PAGE_CONFIG.margin; // Reset Y
      return true;
    }
    return false;
  };

  // --- START DOCUMENT GENERATION ---

  // === HEADER ===
  // Logo / Brand Name
  if (!removeBranding) {
    drawText('InvoicePK', PAGE_CONFIG.margin, y + 6, { 
      size: 22, 
      weight: 'bold', 
      color: COLORS.primary 
    });
    drawText('Professional Invoice Management', PAGE_CONFIG.margin, y + 12, { 
      size: 8, 
      color: COLORS.lightText 
    });
  } else {
    // If branding off, show Sender Name prominent
    drawText(invoice.senderName || 'INVOICE', PAGE_CONFIG.margin, y + 6, { 
      size: 20, 
      weight: 'bold', 
      color: COLORS.secondary 
    });
  }

  // Invoice Details (Right Aligned)
  drawText('INVOICE', rightColX, y + 6, { 
    size: 24, 
    weight: 'bold', 
    color: COLORS.secondary, 
    align: 'right' 
  });
  drawText(`# ${invoice.invoiceNumber}`, rightColX, y + 13, { 
    size: 10, 
    weight: 'bold', 
    color: COLORS.text, 
    align: 'right' 
  });

  y += 25;

  // Divider Line
  doc.setDrawColor(...COLORS.primary);
  doc.setLineWidth(0.8);
  doc.line(PAGE_CONFIG.margin, y, pageWidth - PAGE_CONFIG.margin, y);
  
  y += 10;

  // === INFO GRID (FROM / TO / DATES) ===
  const col1X = PAGE_CONFIG.margin;
  const col2X = PAGE_CONFIG.margin + 70; // Middle column
  const col3X = pageWidth - PAGE_CONFIG.margin - 60; // Right box

  // -- FROM SECTION --
  drawText('FROM:', col1X, y, { size: 8, weight: 'bold', color: COLORS.lightText });
  y += 5;
  const senderHeight = drawText(invoice.senderName || 'Sender Name', col1X, y, { 
    size: 10, 
    weight: 'bold', 
    maxWidth: 60 
  });
  
  // -- TO SECTION --
  let midY = y - 5; // Reset Y for middle column
  drawText('BILL TO:', col2X, midY, { size: 8, weight: 'bold', color: COLORS.lightText });
  midY += 5;
  const clientHeight = drawText(invoice.clientName, col2X, midY, { 
    size: 10, 
    weight: 'bold', 
    maxWidth: 60 
  });

  // Determine max height used by addresses to push Y down
  const maxAddrHeight = Math.max(senderHeight, clientHeight, 15);

  // -- DATES & STATUS BOX (Right Side) --
  // Box Background
  const boxY = y - 10;
  doc.setFillColor(...COLORS.accentBg);
  doc.roundedRect(col3X, boxY, 60 + PAGE_CONFIG.margin, 35, 2, 2, 'F');

  let boxTextY = boxY + 8;
  const boxLabelX = col3X + 5;
  const boxValueX = pageWidth - PAGE_CONFIG.margin - 5;

  // Status
  drawText('Status:', boxLabelX, boxTextY, { size: 9, color: COLORS.text });
  const statusColor = invoice.status === 'paid' ? COLORS.success : COLORS.info;
  drawText(invoice.status.toUpperCase(), boxValueX, boxTextY, { 
    size: 9, 
    weight: 'bold', 
    color: statusColor, 
    align: 'right' 
  });

  boxTextY += 8;
  // Invoice Date
  drawText('Invoice Date:', boxLabelX, boxTextY, { size: 9, color: COLORS.text });
  drawText(format(new Date(invoice.invoiceDate), 'dd MMM yyyy'), boxValueX, boxTextY, { 
    size: 9, 
    weight: 'bold', 
    align: 'right' 
  });

  boxTextY += 8;
  // Due Date
  drawText('Due Date:', boxLabelX, boxTextY, { size: 9, color: COLORS.text });
  drawText(format(new Date(invoice.dueDate), 'dd MMM yyyy'), boxValueX, boxTextY, { 
    size: 9, 
    weight: 'bold', 
    align: 'right' 
  });

  // Move Y below the header/info section
  y = Math.max(y + maxAddrHeight, boxTextY + 15);

  // === PROJECT DESCRIPTION ===
  checkPageBreak(30);

  drawText('PROJECT DESCRIPTION', PAGE_CONFIG.margin, y, { 
    size: 8, 
    weight: 'bold', 
    color: COLORS.lightText 
  });
  y += 5;
  
  const descHeight = drawText(invoice.serviceDescription, PAGE_CONFIG.margin, y, {
    size: 10,
    color: COLORS.text,
    maxWidth: contentWidth
  });

  y += descHeight + 10;

  // === ITEMS TABLE ===
  const hasItems = invoice.items && invoice.items.length > 0;
  
  if (hasItems) {
    // Columns Configuration
    const cols = {
      desc: { x: PAGE_CONFIG.margin + 3, w: contentWidth * 0.5 },
      qty: { x: pageWidth - PAGE_CONFIG.margin - 60, w: 20, align: 'right' },
      rate: { x: pageWidth - PAGE_CONFIG.margin - 35, w: 25, align: 'right' },
      amount: { x: pageWidth - PAGE_CONFIG.margin - 3, w: 30, align: 'right' }
    };

    // Header Drawer Function
    const drawTableHeader = (posY: number) => {
      doc.setFillColor(...COLORS.secondary);
      doc.rect(PAGE_CONFIG.margin, posY, contentWidth, 9, 'F');
      
      const textY = posY + 6;
      drawText('DESCRIPTION', cols.desc.x, textY, { size: 8, weight: 'bold', color: COLORS.white });
      drawText('QTY', cols.qty.x, textY, { size: 8, weight: 'bold', color: COLORS.white, align: 'right' });
      drawText('RATE', cols.rate.x, textY, { size: 8, weight: 'bold', color: COLORS.white, align: 'right' });
      drawText('AMOUNT', cols.amount.x, textY, { size: 8, weight: 'bold', color: COLORS.white, align: 'right' });
      
      return 9; // header height
    };

    // Draw Initial Header
    if (checkPageBreak(20)) {
       y += drawTableHeader(y);
    } else {
       y += drawTableHeader(y);
    }
    
    y += 1; // spacer

    // Loop Items
    invoice.items!.forEach((item, index) => {
      // Calculate row height based on description wrapping
      // We simulate wrapping to know height
      const descLines = doc.splitTextToSize(item.description, cols.desc.w);
      const lineHeight = 5;
      const rowHeight = Math.max(10, (descLines.length * lineHeight) + 6);

      // Check Page Break
      if (checkPageBreak(rowHeight)) {
        y += drawTableHeader(y); // Draw header again on new page
        y += 1;
      }

      // Zebra Striping
      if (index % 2 === 0) {
        doc.setFillColor(...COLORS.accentBg);
        doc.rect(PAGE_CONFIG.margin, y, contentWidth, rowHeight, 'F');
      }

      const rowY = y + 5;
      
      // Description
      doc.setFontSize(9);
      doc.setTextColor(...COLORS.text);
      doc.text(descLines, cols.desc.x, rowY);
      
      // Qty
      drawText(item.quantity.toString(), cols.qty.x, rowY, { size: 9, align: 'right' });
      
      // Rate
      drawText(formatMoney(item.rate, invoice.currency), cols.rate.x, rowY, { size: 9, align: 'right' });
      
      // Amount
      drawText(formatMoney(item.amount, invoice.currency), cols.amount.x, rowY, { size: 9, weight: 'bold', align: 'right' });

      y += rowHeight;
      
      // Divider Line
      doc.setDrawColor(...COLORS.border);
      doc.setLineWidth(0.2);
      doc.line(PAGE_CONFIG.margin, y, pageWidth - PAGE_CONFIG.margin, y);
    });
  }

  y += 10;

  // === TOTALS & NOTES SECTION ===
  // Calculate Totals
  const totalAmount = hasItems 
    ? invoice.items!.reduce((sum, item) => sum + item.amount, 0) 
    : invoice.amount;
  
  const convertedAmount = invoice.currency === 'USD' 
    ? totalAmount * invoice.conversionRate 
    : totalAmount / invoice.conversionRate;
  const convertedCurrency = invoice.currency === 'USD' ? 'PKR' : 'USD';

  // Space check for bottom section (~60mm needed)
  checkPageBreak(60);

  const bottomSectionY = y;
  const notesWidth = contentWidth * 0.55;
  const totalsWidth = contentWidth * 0.40;
  const totalsX = pageWidth - PAGE_CONFIG.margin - totalsWidth;

  // -- LEFT SIDE: NOTES --
  if (invoice.notes) {
    drawText('NOTES & TERMS', PAGE_CONFIG.margin, y + 4, { 
      size: 8, 
      weight: 'bold', 
      color: COLORS.lightText 
    });
    
    y += 9;
    
    drawText(invoice.notes, PAGE_CONFIG.margin, y, {
      size: 8,
      color: COLORS.lightText,
      maxWidth: notesWidth
    });
  }

  // -- RIGHT SIDE: TOTALS --
  let totalsY = bottomSectionY;
  
  // Background Box for Totals
  doc.setFillColor(...COLORS.accentBg);
  doc.roundedRect(totalsX, totalsY, totalsWidth, 45, 2, 2, 'F');

  totalsY += 8;
  const labelX = totalsX + 5;
  const valX = pageWidth - PAGE_CONFIG.margin - 5;

  // Subtotal
  drawText(`Subtotal (${invoice.currency})`, labelX, totalsY, { size: 9, color: COLORS.lightText });
  drawText(formatMoney(totalAmount, invoice.currency), valX, totalsY, { 
    size: 10, 
    weight: 'bold', 
    align: 'right' 
  });

  totalsY += 8;
  // Exchange Rate
  drawText('Exchange Rate', labelX, totalsY, { size: 9, color: COLORS.lightText });
  drawText(`1 USD = ${invoice.conversionRate.toFixed(2)} PKR`, valX, totalsY, { 
    size: 9, 
    align: 'right' 
  });

  totalsY += 10;
  // Divider
  doc.setDrawColor(...COLORS.border);
  doc.line(totalsX + 5, totalsY, pageWidth - PAGE_CONFIG.margin - 5, totalsY);
  
  totalsY += 8;
  
  // GRAND TOTAL
  drawText(`TOTAL (${convertedCurrency})`, labelX, totalsY + 2, { 
    size: 11, 
    weight: 'bold', 
    color: COLORS.primary 
  });
  
  drawText(formatMoney(convertedAmount, convertedCurrency), valX, totalsY + 2, { 
    size: 14, 
    weight: 'bold', 
    color: COLORS.primary, 
    align: 'right' 
  });

  // Finalize
  drawFooter(pageNumber); // Footer on last page
  
  // Save
  doc.save(`${invoice.invoiceNumber || 'Invoice'}.pdf`);
};
