import { format } from 'date-fns';

interface InvoicePreviewProps {
  clientName: string;
  serviceDescription: string;
  amount: number;
  currency: 'USD' | 'PKR';
  conversionRate: number;
  invoiceNumber?: string;
  status?: 'draft' | 'sent' | 'paid';
  createdAt?: Date;
}

export const InvoicePreview = ({
  clientName,
  serviceDescription,
  amount,
  currency,
  conversionRate,
  invoiceNumber = 'INV-PREVIEW',
  status = 'draft',
  createdAt = new Date(),
}: InvoicePreviewProps) => {
  const formatCurrency = (value: number, curr: string) => {
    return new Intl.NumberFormat('en-PK', {
      style: 'currency',
      currency: curr,
      minimumFractionDigits: 0,
      maximumFractionDigits: 2,
    }).format(value);
  };

  const convertedAmount = currency === 'USD' 
    ? amount * conversionRate 
    : amount / conversionRate;
  const convertedCurrency = currency === 'USD' ? 'PKR' : 'USD';

  const getStatusColor = () => {
    switch (status) {
      case 'paid': return 'text-green-600';
      case 'sent': return 'text-blue-600';
      default: return 'text-slate-500';
    }
  };

  return (
    <div className="bg-white text-slate-900 p-8 rounded-lg shadow-lg border border-slate-200 min-h-[600px]">
      {/* Header */}
      <div className="flex justify-between items-start mb-4">
        <div>
          <h1 className="text-2xl font-bold text-orange-500">InvoicePK</h1>
          <p className="text-sm text-slate-500">Professional Invoice Management</p>
        </div>
        <h2 className="text-3xl font-bold text-slate-900">INVOICE</h2>
      </div>
      
      {/* Accent Line */}
      <div className="h-0.5 bg-orange-500 mb-6" />
      
      {/* Invoice Details */}
      <div className="flex justify-between mb-2 text-sm">
        <div>
          <span className="text-slate-500">Invoice Number: </span>
          <span className="font-semibold">{invoiceNumber}</span>
        </div>
        <div>
          <span className="text-slate-500">Date: </span>
          <span className="font-semibold">{format(createdAt, 'MMM dd, yyyy')}</span>
        </div>
      </div>
      
      <div className="text-sm mb-6">
        <span className="text-slate-500">Status: </span>
        <span className={`font-semibold capitalize ${getStatusColor()}`}>{status}</span>
      </div>
      
      {/* Bill To Section */}
      <div className="bg-slate-50 rounded-lg p-4 mb-6">
        <p className="text-xs font-bold text-orange-500 mb-2">BILL TO</p>
        <p className="text-lg font-bold text-slate-900">
          {clientName || <span className="text-slate-400 italic">Client name...</span>}
        </p>
      </div>
      
      {/* Service Description */}
      <div className="mb-6">
        <p className="text-xs font-bold text-orange-500 mb-2">SERVICE DESCRIPTION</p>
        <div className="h-px bg-slate-200 mb-3" />
        <p className="text-slate-700 whitespace-pre-wrap">
          {serviceDescription || <span className="text-slate-400 italic">Service description...</span>}
        </p>
      </div>
      
      {/* Amount Section */}
      <div className="h-px bg-slate-200 mb-4" />
      
      <div className="bg-slate-50 rounded-lg p-4 mb-4">
        {/* Original Amount */}
        <div className="flex justify-between items-center mb-3">
          <span className="text-sm text-slate-500">Amount ({currency})</span>
          <span className="text-lg font-bold text-slate-900">
            {amount > 0 ? formatCurrency(amount, currency) : '--'}
          </span>
        </div>
        
        {/* Conversion Rate */}
        <div className="flex justify-between items-center mb-3">
          <span className="text-sm text-slate-500">Conversion Rate</span>
          <span className="text-sm text-slate-700">1 USD = {conversionRate.toFixed(2)} PKR</span>
        </div>
        
        {/* Converted Amount */}
        <div className="flex justify-between items-center">
          <span className="text-sm text-slate-500">Converted Amount ({convertedCurrency})</span>
          <span className="text-lg font-bold text-orange-500">
            {amount > 0 ? formatCurrency(convertedAmount, convertedCurrency) : '--'}
          </span>
        </div>
      </div>
      
      {/* Total */}
      <div className="bg-orange-500 text-white rounded-lg p-4 flex justify-between items-center mb-6">
        <span className="font-bold">TOTAL AMOUNT</span>
        <span className="text-xl font-bold">
          {amount > 0 ? formatCurrency(amount, currency) : '--'}
        </span>
      </div>
      
      {/* Footer */}
      <div className="h-px bg-slate-200 mb-4" />
      <div className="text-center">
        <p className="text-sm text-slate-500 mb-1">Thank you for your business!</p>
        <p className="text-xs text-slate-400">Generated by InvoicePK</p>
      </div>
    </div>
  );
};
